version: "3.9"
services:
  aria-daemon:
    image: "zkhan93/aria2-daemon:latest"
    ports:
      - "6800:6800"
    volumes:
      - downloads:/downloads
      - completed:/completed
    restart: unless-stopped
    environment:
      SECRET: <replace with rpc secret>
  aria-web:
    image: "zkhan93/aria2-webui:latest"
    ports:
      - "8080:80"
    restart: unless-stopped

volumes:
    downloads:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: <replace with path to store downloading files>
    completed:
      driver: local
      driver_opts:
          o: bind
          type: none
          device: <replace with path to store completed downloads>
